# Generated by Django 5.1 on 2024-08-30 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sportinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetail',
            old_name='joining_date',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
